version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: experiments
      POSTGRES_USER: experiments_user
      POSTGRES_PASSWORD: experiments_user_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: experiments
      DB_USER: experiments_user
      DB_PASSWORD: experiments_user_password
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
