sonar.projectKey=advertisement
sonar.projectName=Advertisement Parent
sonar.host.url=http://localhost:9099
sonar.token=sqa_1a23c3314005ad2fc5eebc25138bd6e57307d2ca

sonar.sources=\
  sql-engine/src/main/java,\
  advertisement-contracts/src/main/java,\
  audit-spring-boot-starter/src/main/java,\
  attachment-spring-boot-starter/src/main/java,\
  advertisement-app/src/main/java

sonar.java.source=25
sonar.java.binaries=\
  sql-engine/target/classes,\
  advertisement-contracts/target/classes,\
  audit-spring-boot-starter/target/classes,\
  attachment-spring-boot-starter/target/classes,\
  advertisement-app/target/classes

sonar.exclusions=**/target/**,**/node_modules/**
sonar.scm.disabled=true
