sonar.projectKey=advertisement
sonar.projectName=Advertisement Parent
sonar.host.url=http://localhost:9099
sonar.token=sqa_1a23c3314005ad2fc5eebc25138bd6e57307d2ca

sonar.sources=\
  query-starter/src/main/java,\
  platform-commons/src/main/java,\
  audit-spring-boot-starter/src/main/java,\
  attachment-spring-boot-starter/src/main/java,\
  marketplace-app/src/main/java

sonar.java.source=25
sonar.java.binaries=\
  query-starter/target/classes,\
  platform-commons/target/classes,\
  audit-spring-boot-starter/target/classes,\
  attachment-spring-boot-starter/target/classes,\
  marketplace-app/target/classes

sonar.exclusions=**/target/**,**/node_modules/**
sonar.scm.disabled=true
